server {
    listen 443 ssl;
    server_name palworld.lukeholland.dev;

    ssl_certificate /etc/letsencrypt/live/palworld.lukeholland.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/palworld.lukeholland.dev/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/palworld.lukeholland.dev/chain.pem;
    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

    location / {
        proxy_pass http://palworld-live-map:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_read_timeout 30s;
        proxy_send_timeout 30s;
    }
}
